### ISSUE TITLE
Projeto sem atualização

### ISSUE THREAD

**Issue by jlsilva01** [Mateuslh/agiotagem_bank#1]
@Mateuslh o repositório não teve nenhuma alteração há quase uma semana.
Sugiro revalidarem a distribução das tarefas para que tenha commits frequentes neste repositório indicando o trabalho contínuo do mesmo.
Dúvida, me avisem.

**Comment by mateuslh** [comment]
Ola @jlsilva01,

Infelizmente não houve avanço nessa semana, entretanto seguiremos da seguinte forma...

Cada subgrupo ficará responsável por criar suas próprias issues, sendo então o time:
# back-end | database
- @Mateuslh 
- @marcosgoudinho
# front-end | slide | doc word
- @LuanCS27
- @JoaozinhoProgramation
- @joaodagostin
- @f5joaodanieldeliz 

Os tickets criados serão marcados com as tags ja criadas back-end, front-end, banco, tags defualt (ex: documentation) e possíveis novas tags conforme necessário.

first issue de exemplo #2
