### ISSUE TITLE
🚅 Start da aplicação spring  e criação dos models 

### ISSUE THREAD

**Issue by mateuslh** [Mateuslh/agiotagem_bank#2]
# Criação dos **models** da aplicação spring
#### A mesma deve ter como intuito apenas **refletir** as entidades do banco postgres, competindo a ele a **validação e manipulação** dos dados.

O modelo do banco a ser persistido foi disponibilizado no commit d7f8d95ba20ab6dcee66652e95f7b75cbf05884d

A aplicação spring deve ser iniciada dentro do próprio repositório do trabalho, dentro da pasta back-end

**Comment by mateuslh** [comment]
Deve que os models sejam criados se deve:



- [x] Ser refatorado os tipos e dados do DB. #4
- [x] Criar as dependências da conta de destino do empréstimo. #3

**Comment by Mateuslh** [comment]
models criados
